1. Provide examples of three different instruction mnemonics.
정답: MOV, ADD, SUB, JMP, CALL 등

2. What is a calling convention, and how is it used in assembly language declarations?
정답: 함수나 프로시저 호출 시 인자 전달 순서와 스택 정리 주체를 정의하는 규칙입니다. .MODEL 지시어와 함께 stdcall이나 c 등으로 선언하여 사용합니다.

3. How do you reserve space for the stack in a program?
정답: .STACK 지시어를 사용합니다.

4. Explain why the term assembler language is not quite correct.
정답: '어셈블러(Assembler)'는 코드를 기계어로 번역하는 번역기(프로그램) 자체를 뜻하며, 언어의 정확한 명칭은 '어셈블리어(Assembly language)'이기 때문입니다.

5. Explain the difference between big endian and little endian. Also, look up the origins of this
term on the Web.
정답: 리틀 엔디안은 최하위 바이트(LSB)를 가장 낮은 메모리 주소에 저장하고, 빅 엔디안은 최상위 바이트(MSB)를 가장 낮은 주소에 저장합니다. 기원은 조너선 스위프트의 소설 《걸리버 여행기》입니다.

6. Why might you use a symbolic constant rather than an integer literal in your code?
정답: 코드의 가독성을 높이고 프로그램 유지보수를 쉽게 하기 위해서입니다.

7. How is a source file different from a listing file?
정답: 소스 파일은 프로그래머가 작성한 어셈블리어 텍스트 파일이며, 리스팅 파일은 어셈블러가 생성한 출력 파일로 소스 코드와 번역된 기계어 코드 등의 상세 정보가 포함되어 있습니다.

8. How are data labels and code labels different?
정답: 데이터 레이블은 메모리에 저장된 변수의 위치를 나타내며 뒤에 콜론(:)이 없고, 코드 레이블은 실행할 명령어의 위치를 나타내며 이름 뒤에 콜론(:)을 붙입니다.

9. (True/False): An identifier cannot begin with a numeric digit.
정답: True

10. (True/False): A hexadecimal literal may be written as 0x3A.
정답: False

11. (True/False): Assembly language directives execute at runtime.
정답: False

12. (True/False): Assembly language directives can be written in any combination of uppercase
and lowercase letters.
정답: True

13. Name the four basic parts of an assembly language instruction.
정답: 레이블(Label), 명령어 니모닉(Mnemonic), 피연산자(Operand), 주석(Comment)

14. (True/False): MOV is an example of an instruction mnemonic.
정답: True

15. (True/False): A code label is followed by a colon (:), but a data label does not end with a
colon.
정답: True

16. Show an example of a block comment.
COMMENT !
이곳은 여러 줄의
블록 주석 영역입니다.
!

17. Why is it not a good idea to use numeric addresses when writing instructions that access
variables?
정답: 코드나 데이터가 수정될 때마다 변수의 실제 메모리 주소가 변경되어, 프로그래머가 직접 다시 계산하고 수정해야 하므로 매우 비효율적이기 때문입니다.

18. What type of argument must be passed to the ExitProcess procedure?
정답: 32비트 정수형 반환 코드(Return code)

19. Which directive ends a procedure?
정답: ENDP

20. In 32-bit mode, what is the purpose of the identifier in the END directive?
정답: 프로그램의 시작 진입점(Entry point)을 지정하기 위함입니다.

21. What is the purpose of the PROTO directive?
정답: 프로시저의 프로토타입(원형)을 선언하기 위함입니다.

22. (True/False): An Object file is produced by the Linker.
정답: False

23. (True/False): A Listing file is produced by the Assembler.
정답: True

24. (True/False): A link library is added to a program just before producing an Executable file.
정답: True

25. Which data directive creates a 32-bit signed integer variable?
정답: SDWORD

26. Which data directive creates a 16-bit signed integer variable?
정답: SWORD

27. Which data directive creates a 64-bit unsigned integer variable?
정답: QWORD

28. Which data directive creates an 8-bit signed integer variable?
정답: SBYTE

29. Which data directive creates a 10-byte packed BCD variable?
정답: TBYTE

1. Define four symbolic constants that represent integer 25 in decimal, binary, octal,
and hexadecimal formats.
정답:   DEC_VAL = 25 (또는 DEC_VAL = 25d)   BIN_VAL = 00011001b   OCT_VAL = 31o (또는 31q)   HEX_VAL = 19h   

2. Find out, by trial and error, if a program can have multiple code and data segments.
정답: 여러 개의 세그먼트를 가질 수 있습니다 (Yes).

3. Create a data definition for a doubleword that stored it in memory in big endian
format.
정답: (예시 값 12345678h 기준) myVar BYTE 12h, 34h, 56h, 78h

4. Find out if you can declare a variable of type DWORD and assign it a negative
value. What does this tell you about the assembler’s type checking?
정답: 할당할 수 있습니다 (예: myVar DWORD -1). 이는 어셈블러가 부호(Signed/Unsigned)에 대한 타입 검사를 엄격하게 하지 않는다는 것을 의미합니다.

5. Write a program that contains two instructions: (1) add the number 5 to the EAX
register, and (2) add 5 to the EDX register. Generate a listing file and examine the
machine code generated by the assembler. What differences, if any, did you find
between the two instructions?
정답: 두 명령어의 목적지 레지스터를 식별하는 기계어 바이트(ModR/M 필드 또는 레지스터 필드) 부분의 값이 다릅니다.

6. Given the number 456789ABh, list out its byte values in little-endian order.
정답: ABh, 89h, 67h, 45h

7. Declare an array of 120 uninitialized unsigned doubleword values.
정답: myArray DWORD 120 DUP(?)

8. Declare an array of byte and initialize it to the first 5 letters of the alphabet.
정답: myArray BYTE "ABCDE" (또는 myArray BYTE 'A', 'B', 'C', 'D', 'E')

9. Declare a 32-bit signed integer variable and initialize it with the smallest possible
negative decimal value. (Hint: Refer to integer ranges in Chapter 1.)
정답: myVar SDWORD -2147483648

10. Declare an unsigned 16-bit integer variable named wArray that uses three initializers.
정답: wArray WORD 10, 20, 30

11. Declare a string variable containing the name of your favorite color. Initialize it as
a nullterminated string.
정답: (예시: 파란색) myColor BYTE "Blue", 0

12. Declare an uninitialized array of 50 signed doublewords named dArray.
정답: dArray SDWORD 50 DUP(?)

13. Declare a string variable containing the word “TEST” repeated 500 times.
정답: myString BYTE 500 DUP("TEST")

14. Declare an array of 20 unsigned bytes named bArray and initialize all elements to
zero.
정답: bArray BYTE 20 DUP(0)

15. Show the order of individual bytes in memory (lowest to highest) for the following doubleword variable:
val1 DWORD 87654321h
정답: 21h, 43h, 65h, 87h

1. Integer Expression Calculation
Using the AddTwo program from Section 3.2 as a reference, write a program that calculates the
following expression, using registers: A = (A + B) − (C + D). Assign integer values to the EAX,
EBX, ECX, and EDX registers.

.386
.model flat,stdcall
.stack 4096
ExitProcess PROTO, dwExitCode:DWORD

.code
main PROC
    ; 초기 값 할당 (예의상 임의의 값 지정)
    mov eax, 10      ; A = 10
    mov ebx, 20      ; B = 20
    mov ecx, 5       ; C = 5
    mov edx, 2       ; D = 2

    ; 수식 계산: A = (A + B) - (C + D)
    add eax, ebx     ; EAX = A + B (10 + 20 = 30)
    add ecx, edx     ; ECX = C + D (5 + 2 = 7)
    sub eax, ecx     ; EAX = (A + B) - (C + D) (30 - 7 = 23)

    INVOKE ExitProcess, 0
main ENDP
END main

2. Symbolic Integer Constants
Write a program that defines symbolic constants for all seven days of the week. Create an array
variable that uses the symbols as initializers.

; 기호 상수 정의
MONDAY = 1
TUESDAY = 2
WEDNESDAY = 3
THURSDAY = 4
FRIDAY = 5
SATURDAY = 6
SUNDAY = 7

.data
; 상수를 활용한 배열 초기화
daysArray BYTE MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY

3. Data Definitions
Write a program that contains a definition of each data type listed in Table 3-2 in Section 3.4.
Initialize each variable to a value that is consistent with its data type.

.data
val1 BYTE   255             ; 8-bit unsigned
val2 SBYTE  -128            ; 8-bit signed
val3 WORD   65535           ; 16-bit unsigned
val4 SWORD  -32768          ; 16-bit signed
val5 DWORD  4294967295      ; 32-bit unsigned
val6 SDWORD -2147483648     ; 32-bit signed
val7 QWORD  0FFFFFFFFFFFFFFFFh ; 64-bit integer
val8 TBYTE  10000000000000000h ; 80-bit (10-byte) integer
val9 REAL4  1.5             ; 32-bit IEEE Short Real
val10 REAL8 3.141592        ; 64-bit IEEE Long Real

4. Symbolic Text Constants
Write a program that defines symbolic names for several string literals (characters between
quotes). Use each symbolic name in a variable definition.

; 텍스트 상수 정의
msgHello TEXTEQU <"Hello, World!", 0>
msgWarning TEXTEQU <"Warning: Low Memory", 0>

.data
; 변수에 텍스트 상수 적용
greeting BYTE msgHello
alertMessage BYTE msgWarning

5. Listing File for AddTwoSum
Generate a listing file for the AddTwoSum program and write a description of the machine code
bytes generated for each instruction. You might have to guess at some of the meanings of the
byte values.

00000000                    .code
00000000                    main PROC
00000000  B8 00000005           mov eax, 5
00000005  83 C0 06              add eax, 6
00000008  E8 00000000 R         call ExitProcess
0000000D                    main ENDP

6. AddVariables Program
Modify the AddVariables program so it uses 64-bit variables. Describe the syntax errors generated by the assembler and what steps you took to resolve the errors.

.data
val1 QWORD 1000h
val2 QWORD 2000h

.code
mov rax, val1  ; 피연산자 양쪽 모두 64비트로 일치함
add rax, val2
